name: Build and Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish OpenJDK 8u242 Alpine 3.11.3
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fadeltd/openjdk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: openjdk/jdk-8/Dockerfile
        tags: "latest, 8-alpine3.11"
        tag_names: true
    - name: Publish Base Android NDK
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fadeltd/alpine-android-ndk-base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: android-base/Dockerfile
        tags: "latest"
        tag_names: true
    - name: Publish Android NDK with SDK 28
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fadeltd/alpine-android-ndk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: android-sdk/sdk-28/Dockerfile
        tags: "sdk-28"
    - name: Publish Android NDK with SDK 29
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fadeltd/alpine-android-ndk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: android-sdk/sdk-29/Dockerfile
        tags: "latest, sdk-29"
    - name: Publish Base Android NDK with Ruby 2.7.0
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fadeltd/alpine-android-ndk-ruby-base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: android-ruby/base/Dockerfile
        tags: "latest"
        tag_names: true
    - name: Publish Android NDK with SDK 28 and Ruby
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fadeltd/alpine-android-ndk-ruby
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: android-ruby/sdk-28/Dockerfile
        tags: "2.7.0-sdk28"
    - name: Publish Android NDK with SDK 29 and Ruby
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fadeltd/alpine-android-ndk-ruby
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: android-ruby/sdk-29/Dockerfile
        tags: "latest, 2.7.0-sdk29"
